spring.application.name=Survey-It
server.port=8080
server.servlet.context-path=/api  


spring.datasource.url=jdbc:postgresql://localhost:5432/Survey_IT
spring.datasource.username=postgres
spring.datasource.password=administrateur
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA and Hibernate settings
spring.jpa.properties.hibernate.format_sql=true 
spring.jpa.open-in-view=false  

# Logging configuration
logging.level.org.springframework=INFO  # Set logging level for Spring framework
logging.level.root=INFO  # Set root logging level
logging.file.name=logs/application.log  # Log file location
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n  # Log pattern

# Validation properties
spring.validation.message-bundle=messages  # Custom validation messages file




